replicaCount: 1

image:
  repository: minio/minio
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 9000

consolePort: 9001

resources: {}

storage:
  size: 5Gi
  storageClass: ""
  accessMode: ReadWriteOnce
  annotations: {}

secret:
  rootUser: minio
  rootPassword: minio123

nodeSelector: {}
tolerations: []
affinity: {}
