# syntax=docker/dockerfile:1

FROM node:20-slim
WORKDIR /app
COPY server_v2/package.json ./package.json
COPY server_v2/package-lock.json* ./ || true
RUN npm i --omit=dev
COPY server_v2/. .
RUN npm run build
ARG WORKER_TYPE=cpu
ENV NODE_ENV=production
EXPOSE 3001
CMD ["sh", "-c", "node dist/worker.$WORKER_TYPE.js"]
