apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgres.fullname" . }}-pvc
  labels:
    {{ include "postgres.labels" . | indent 4 }}
  annotations:
    {{- range $key, $value := .Values.storage.annotations }}
    {{ $key }}: {{ quote $value }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
