apiVersion: v1
kind: Service
metadata:
  name: {{ include "temporal.fullname" . }}
  labels:
    {{ include "temporal.labels" . | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "temporal.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
