import { Router } from 'express';
import { healthRouter } from './routes/health.js';
import { tasksRouter } from './routes/tasks.js';
import { eventsRouter } from './routes/events.js';
import { languagesRouter } from './routes/languages.js';
import { pipelineRouter } from './routes/pipeline.js';
import { aiRouter } from './routes/ai.js';
import { abRouter } from './routes/ab.js';
import { publishRouter } from './routes/publish.js';
import { analyticsRouter } from './routes/analytics.js';
import { metricsRouter } from './routes/metrics.js';
import { authRouter } from './routes/auth.js';
import { uploadsRouter } from './routes/uploads.js';
import { docsRouter } from './routes/docs.js';
import { orgsRouter } from './routes/orgs.js';
import { apiKeysRouter } from './routes/apikeys.js';
import { oauthGoogleRouter } from './routes/oauth-google.js';
import { publishYouTubeRouter } from './routes/publish-youtube.js';
import { adminDeadlettersRouter } from './routes/admin/deadletters.js';
import { adminEventsRouter } from './routes/admin/events.js';
import { adminFlagsRouter } from './routes/admin/flags.js';
import { adminWebhooksRouter } from './routes/admin/webhooks.js';
import { billingRouter } from './routes/billing.js';
import { filesRouter } from './routes/files.js';
import { mediaRouter } from './routes/media.js';
import { selftestRouter } from './routes/selftest.js';
import { devWebhookRouter } from './routes/dev-webhook.js';
import { env } from './utils/env.js';

export const buildV1Router = () => {
  const router = Router();
  router.use(healthRouter);
  router.use(tasksRouter);
  router.use(eventsRouter);
  router.use(languagesRouter);
  router.use(pipelineRouter);
  router.use(aiRouter);
  router.use(abRouter);
  router.use(publishRouter);
  router.use(analyticsRouter);
  router.use(metricsRouter);
  router.use(authRouter);
  router.use(uploadsRouter);
  router.use(orgsRouter);
  router.use(apiKeysRouter);
  router.use(oauthGoogleRouter);
  router.use(publishYouTubeRouter);
  router.use(adminDeadlettersRouter);
  router.use(adminEventsRouter);
  router.use(adminFlagsRouter);
  router.use(adminWebhooksRouter);
  router.use(billingRouter);
  router.use(filesRouter);
  router.use(mediaRouter);
  if (env.DEV_TOOLS) {
    router.use(selftestRouter);
    router.use(devWebhookRouter);
  }
  router.use(docsRouter);
  return router;
};
