apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{ include "minio.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "minio.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "minio.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: minio
          image: {{ include "minio.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - minio
            - server
            - /data
            - --console-address
            - ":{{ .Values.consolePort }}"
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.fullname" . }}-secret
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio.fullname" . }}-secret
                  key: MINIO_ROOT_PASSWORD
          resources:
{{ toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
            - containerPort: {{ .Values.consolePort }}
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /minio/health/live
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /minio/health/ready
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "minio.fullname" . }}-pvc
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 6 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 6 }}
{{- end }}
