apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-config
  labels:
    {{ include "api.labels" . | indent 4 }}
data:
{{- if .Values.env }}
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ quote $value }}
{{- end }}
{{- else }}
  NODE_ENV: production
{{- end }}
