apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}-secret
type: Opaque
stringData:
  JWT_SECRET: {{ default "dev-secret" .Values.secret.jwtSecret | quote }}
  KMS_SECRET: {{ default "kms-secret" .Values.secret.kmsSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  MINIO_ACCESS_KEY: {{ .Values.minio.accessKey | quote }}
  MINIO_SECRET_KEY: {{ .Values.minio.secretKey | quote }}
