import { mkdir, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';
import type { AsrProvider, AsrSegment } from './index.js';

const formatTimestamp = (seconds: number) => {
  const date = new Date(seconds * 1000);
  const hh = String(date.getUTCHours()).padStart(2, '0');
  const mm = String(date.getUTCMinutes()).padStart(2, '0');
  const ss = String(date.getUTCSeconds()).padStart(2, '0');
  const ms = String(date.getUTCMilliseconds()).padStart(3, '0');
  return `${hh}:${mm}:${ss},${ms}`;
};

const segmentsToSrt = (segments: AsrSegment[]) =>
  segments
    .map(
      (segment, index) =>
        `${index + 1}\n${formatTimestamp(segment.start)} --> ${formatTimestamp(segment.end)}\n${segment.text.trim()}\n`
    )
    .join('\n');

const ensureDir = async (filePath: string) => {
  await mkdir(dirname(filePath), { recursive: true });
};

export const mockAsrProvider: AsrProvider = {
  name: 'mock-asr',
  async transcribe({ language, outputPath }) {
    const segments: AsrSegment[] = [
      {
        id: 1,
        start: 0,
        end: 4,
        text: `Transcription segment for ${(language ?? 'en-US').toUpperCase()}`
      },
      {
        id: 2,
        start: 4,
        end: 8,
        text: 'Generated by mock ASR provider'
      }
    ];
    const srt = segmentsToSrt(segments);
    await ensureDir(outputPath);
    await writeFile(outputPath, srt, 'utf8');
    return {
      srtPath: outputPath,
      segments,
      metrics: {
        provider: 'mock-asr',
        language: language ?? 'en-US',
        mode: 'synthetic'
      }
    };
  }
};
