import { config as loadEnv } from 'dotenv';
import { z } from 'zod';

loadEnv();

const envSchema = z.object({
  NODE_ENV: z.string().optional(),
  PORT: z.coerce.number().int().min(1).default(3001),
  CORS_ORIGIN: z.string().default('http://localhost:5173'),
  DATABASE_URL: z.string().min(1),
  JWT_SECRET: z.string().min(6).default('dev-secret'),
  JWT_EXPIRES: z.string().default('7d'),
  ORG_DEFAULT_NAME: z.string().default('Default Organization'),
  API_KEY_PREFIX: z.string().default('ytb_'),
  ASR_PROVIDER: z.enum(['mock', 'openai']).default('mock'),
  OPENAI_API_KEY: z.string().optional(),
  OPENAI_MODEL: z.string().default('gpt-4o-mini'),
  TTS_PROVIDER: z.enum(['mock', 'elevenlabs', 'azure']).default('mock'),
  ELEVEN_API_KEY: z.string().optional(),
  ELEVENLABS_API_KEY: z.string().optional(),
  ELEVENLABS_VOICE_ID: z.string().default('EXAVITQu4vr4xnSDxMaL'),
  TTS_SAMPLE_RATE: z.coerce.number().int().min(8000).max(48000).default(22050),
  AZURE_SPEECH_KEY: z.string().optional(),
  AZURE_SPEECH_REGION: z.string().optional(),
  RUNWAY_API_KEY: z.string().optional(),
  RUNWAY_API_BASE: z.string().url().default('https://api.runwayml.com'),
  RUNWAY_PRICE_PER_MIN_FLASH: z.coerce.number().min(0).default(0),
  RUNWAY_PRICE_PER_MIN_ALPHA: z.coerce.number().min(0).default(0),
  RUNWAY_MAX_CONCURRENCY: z.coerce.number().int().min(1).default(4),
  LUMA_API_KEY: z.string().optional(),
  LUMA_API_BASE: z.string().url().default('https://api.luma.ai'),
  LUMA_PRICE_PER_MIN_1080: z.coerce.number().min(0).default(0),
  LUMA_PRICE_PER_MIN_2K: z.coerce.number().min(0).default(0),
  LUMA_PRICE_PER_MIN_4K: z.coerce.number().min(0).default(0),
  LUMA_MAX_CONCURRENCY: z.coerce.number().int().min(1).default(2),
  HAIPER_API_KEY: z.string().optional(),
  HAIPER_API_BASE: z.string().url().default('https://api.haiper.ai'),
  HAIPER_PRICE_PER_MIN_1080: z.coerce.number().min(0).default(0),
  HAIPER_MAX_CONCURRENCY: z.coerce.number().int().min(1).default(6),
  REPLICATE_API_TOKEN: z.string().optional(),
  REPLICATE_API_BASE: z.string().url().default('https://api.replicate.com'),
  REPLICATE_MAX_CONCURRENCY: z.coerce.number().int().min(1).default(3),
  DOMOAI_API_KEY: z.string().optional(),
  DOMOAI_API_BASE: z.string().url().default('https://api.domo.ai'),
  DOMOAI_PRICE_PER_MIN_EFFECT: z.coerce.number().min(0).default(0),
  DOMOAI_MAX_CONCURRENCY: z.coerce.number().int().min(1).default(4),
  CONCURRENCY: z.coerce.number().int().min(1).default(2),
  FAIL_RATE: z.coerce.number().min(0).max(100).default(0),
  WORK_DIR: z.string().default('./workspace'),
  QUEUE_DRIVER: z.enum(['memory', 'redis']).default('memory'),
  WORKER_MODE: z.enum(['inline', 'fork']).default('inline'),
  QUEUE_CONCURRENCY: z.coerce.number().int().min(1).default(2),
  QUEUE_MAX_RETRIES: z.coerce.number().int().min(0).default(3),
  QUEUE_RETRY_BASE_MS: z.coerce.number().int().min(100).default(1000),
  QUEUE_RETRY_MAX_MS: z.coerce.number().int().min(1000).default(30000),
  WEBHOOK_RETRY_MAX: z.coerce.number().int().min(1).default(5),
  BLOB_BACKEND: z.enum(['local', 's3']).default('local'),
  S3_BUCKET: z.string().optional(),
  S3_REGION: z.string().optional(),
  S3_ENDPOINT: z.string().optional(),
  S3_ACCESS_KEY: z.string().optional(),
  S3_SECRET_KEY: z.string().optional(),
  S3_ACCESS_KEY_ID: z.string().optional(),
  S3_SECRET_ACCESS_KEY: z.string().optional(),
  S3_FORCE_PATH_STYLE: z.coerce.boolean().default(false),
  TRUST_PROXY: z.string().default('loopback'),
  FFMPEG_PATH: z.string().default('ffmpeg'),
  BURN_RESOLUTION: z.string().default('1920x1080'),
  BURN_CODEC: z.string().default('libx264'),
  BURN_CRF: z.coerce.number().min(0).max(51).default(23),
  BURN_PRESET: z.string().default('medium'),
  RATE_LIMIT_WINDOW: z.coerce.number().int().min(1).default(60),
  RATE_LIMIT_MAX: z.coerce.number().int().min(1).default(120),
  RATE_LIMIT_PER_ORG: z.coerce.number().int().min(1).default(300),
  GEN_QUOTA_MIN_PER_DAY: z.coerce.number().int().min(1).default(120),
  GEN_QUOTA_CONCURRENCY: z.coerce.number().int().min(1).default(2),
  LOUDNESS_TARGET_LUFS: z.coerce.number().default(-14),
  LOUDNESS_RANGE: z.coerce.number().default(12),
  VMAF_MIN: z.coerce.number().min(0).max(100).default(93),
  RENDER_RETRY_MAX: z.coerce.number().int().min(0).default(1),
  QC_ENABLE: z.coerce.boolean().default(false),
  DEFAULT_RENDER_PRESET: z.string().default('2160p:h264:auto'),
  IDEMPOTENCY_TTL_SECONDS: z.coerce.number().int().min(60).default(3600),
  LOG_LEVEL: z.enum(['debug', 'info', 'warn', 'error']).default('info'),
  OTEL_EXPORTER_OTLP_ENDPOINT: z.string().url().default('http://localhost:4318'),
  OTEL_TRACES_SAMPLER: z.string().default('parentbased_traceidratio'),
  OTEL_TRACES_SAMPLER_ARG: z.string().default('0.2'),
  GOOGLE_CLIENT_ID: z.string().optional(),
  GOOGLE_CLIENT_SECRET: z.string().optional(),
  GOOGLE_REDIRECT_URL: z.string().url().default('http://localhost:3001/oauth/google/callback'),
  KMS_SECRET: z.string().min(16, 'KMS_SECRET must be at least 16 characters long'),
  DRY_RUN: z.coerce.boolean().default(true),
  MAX_UPLOAD_MB: z.coerce.number().int().min(1).default(1024),
  ALLOWED_MIME: z.string().default('audio/wav,audio/mpeg,video/mp4,video/mov,application/x-subrip,text/vtt'),
  CLAMAV_HOST: z.string().default('127.0.0.1'),
  CLAMAV_PORT: z.coerce.number().int().min(1).default(3310),
  QUARANTINE_DIR: z.string().default('./workspace/quarantine'),
  PIPELINE_MAX_STAGES: z.coerce.number().int().min(1).max(100).default(30),
  SMTP_HOST: z.string().optional(),
  SMTP_PORT: z.coerce.number().int().min(1).default(587),
  SMTP_USER: z.string().optional(),
  SMTP_PASS: z.string().optional(),
  SLACK_WEBHOOK_URL: z.string().optional(),
  FEISHU_WEBHOOK_URL: z.string().optional(),
  ALERT_FAILRATE_THRESHOLD: z.coerce.number().min(0).max(1).default(0.03),
  ALERT_QUEUE_DEPTH: z.coerce.number().int().min(1).default(100),
  QUOTA_TASKS_PER_DAY: z.coerce.number().int().min(1).default(500),
  QUOTA_RENDER_MIN_PER_DAY: z.coerce.number().int().min(1).default(600),
  QUOTA_STORAGE_GB: z.coerce.number().int().min(1).default(200),
  WORKSPACE_TMP_TTL_HOURS: z.coerce.number().int().min(1).default(24),
  TEMPORAL_HOST: z.string().default('temporal:7233'),
  TEMPORAL_NAMESPACE: z.string().default('default'),
  TEMPORAL_TASK_QUEUE_GPU: z.string().default('video-gpu'),
  TEMPORAL_TASK_QUEUE_CPU: z.string().default('video-cpu'),
  TEMPORAL_WORKFLOW_TASK_QUEUE: z.string().default('video-pipeline'),
  TEMPORAL_SSE_SECRET: z.string().default('temporal-sse-secret'),
  MAX_PAR_SHOTS: z.coerce.number().int().min(1).max(12).default(6),
  STAGE_TIMEOUT_SEC: z.coerce.number().int().min(5).default(300),
  HEARTBEAT_SEC: z.coerce.number().int().min(5).default(15),
  PREEMPTIBLE: z.coerce.boolean().default(false),
  AB_METRIC_PRIMARY: z.string().default('conversions'),
  AB_EXPLORATION_RATE: z.coerce.number().min(0).max(1).default(0.2),
  AB_MIN_IMPRESSIONS: z.coerce.number().int().min(1).default(100),
  AB_COOLDOWN_MIN: z.coerce.number().int().min(0).default(10),
  COLOR_PIPELINE: z.enum(['hdr10', 'hlg', 'bt2020', 'hdr10+']).default('hdr10'),
  PER_TITLE_VMAF_TARGET: z.coerce.number().min(70).max(100).default(93),
  BITRATE_FLOOR_1080P: z.coerce.number().int().min(3000).default(6000),
  BITRATE_FLOOR_1440P: z.coerce.number().int().min(4000).default(10000),
  BITRATE_FLOOR_2160P: z.coerce.number().int().min(8000).default(18000),
  BITRATE_FLOOR_SOURCE: z.coerce.number().int().min(1000).default(2500),
  LIPSYNC_MAX_OFFSET_MS: z.coerce.number().int().min(10).default(80),
  SUBSAFE_MARGIN_PCT: z.coerce.number().min(0).max(50).default(5),
  PGVECTOR_ENABLE: z.coerce.boolean().default(false),
  EMBED_MODEL_NAME: z.string().default('mock-embedder'),
  EMBED_MODEL_DIM: z.coerce.number().int().min(8).default(64),
  SIMILARITY_TOPK: z.coerce.number().int().min(1).default(10),
  DEDUP_SIM_THRESHOLD: z.coerce.number().min(0).max(1).default(0.94),
  DEV_TOOLS: z.coerce.boolean().default(false),
  SELFTEST_ENABLE_EXTERNAL: z.coerce.boolean().default(false),
  SELFTEST_API_KEY: z.string().optional(),
  COST_ROLLUP_CRON: z.string().default('*/5 * * * *'),
  PROVIDER_PRICING_FILE: z.string().default('src/config/providers.cost.json'),
  COST_ALERT_UNIT_COST_SIGMA: z.coerce.number().default(2),
  SLO_TARGET_API: z.coerce.number().min(0).max(1).default(0.995),
  SLO_TARGET_GEN: z.coerce.number().min(0).max(1).default(0.98),
  K8S_ENABLED: z.coerce.boolean().default(false),
  PUBLIC_BASE_URL: z.string().url().default('http://localhost'),
  REGISTRY_URL: z.string().default('ghcr.io/example'),
  IMAGE_TAG: z.string().default('latest'),
  POSTGRES_HOST: z.string().default('postgres'),
  POSTGRES_PORT: z.coerce.number().int().min(1).default(5432),
  POSTGRES_DB: z.string().default('youtube_tool'),
  POSTGRES_USER: z.string().default('postgres'),
  POSTGRES_PASSWORD: z.string().default('changeme'),
  REDIS_URL: z.string().default('redis://redis:6379'),
  MINIO_ENDPOINT: z.string().default('http://minio:9000'),
  MINIO_ACCESS_KEY: z.string().default('minio'),
  MINIO_SECRET_KEY: z.string().default('minio123')
});

export const env = envSchema.parse(process.env);
