apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: youtube-api
spec:
  project: default
  source:
    repoURL: https://github.com/example/youtube-tool
    targetRevision: HEAD
    path: deploy/charts/api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
